//language
export const LOAD_LANGUAGE = 'LOAD_LANGUAGE'

//dialog
export const SHOW_DIALOG = 'SHOW_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'

//snackbar
export const ADD_SNACKBAR_MESSAGE = 'ADD_SNACKBAR_MESSAGE'
export const REMOVE_SNACKBAR_MESSAGE = 'REMOVE_SNACKBAR_MESSAGE'

//form
export const SET_FORM_STATUS = 'SET_FORM_STATUS'
export const SET_FILE_TO_UPLOAD = 'SET_FILE_TO_UPLOAD'
export const SET_FORM_PREVIEW = 'SET_FORM_PREVIEW'